### ISSUE TITLE
Compatibilidad del sistema en Linux

### ISSUE THREAD

**Issue by migyanari** [pedbiefre/InnosoftDiploma#18]
Crear un archivo ejecutable en Linux (.ssh) de la aplicación

**Comment by enrmerver** [comment]
Crear un archivo ejecutable en Linux (.ssh) de la aplicación

**Comment by enrmerver** [comment]
Tras comprobar varias librerias que exportan proyectos python, he concluido con que lo mejor para equipos Windows es la ejecución del archivo .py o el archivo .exe ya creado sin problemas y para Linux lo mejor es ejecutar el archivo con el comando `chmod +x InnosoftDiplomas.py` para dar permisos y luego `./InnosoftDiplomas.py` para su ejecución. Importante tener la línea `#!/usr/bin/python` en ese archivo.

Esto se explicará en el manual cuando se actualice.
