### ISSUE TITLE
Implementar un servidor de integración continua 

### ISSUE THREAD

**Issue by enrmerver** [pedbiefre/InnosoftDiploma#20]
Conectar la aplicación con Travis.

**Comment by pedbiefre** [comment]
Travis no hace build actualmente. Se debe principalmente a lo escrito en script: de .travis.yml https://github.com/pedbiefre/InnosoftDiploma/commit/cf324afa3a7dafd7f4f1fb606ad82e66cf962f70

**Comment by pedbiefre** [comment]
Builds correctas y conectado a codacy https://github.com/pedbiefre/InnosoftDiploma/commit/60cccae4999b82bb440390186463caa2e4d45759
