### ISSUE TITLE
Despliegue de la aplicación

### ISSUE THREAD

**Issue by josgatfer** [pedbiefre/InnosoftDiploma#25]
El objetivo inicial ha sido publicar la aplicación en Snapcraft. Tras encontrarnos con que no logramos hacerlo, hemos probado a generar un .exe mediante Travis.

**Comment by migyanari** [comment]
La creación de un docker es viable pero ineficiente, seguiremos la recomendación de Benavides para publicar el proyecto en Snapcraft.

**Comment by pedbiefre** [comment]
Tras numerosos intentos para publicar el proyecto en Snapcraft no vemos la viabilidad. Resulta muy tedioso y no encontramos suficiente documentación. Hemos decidido desplegar el proyecto con el uso del paquete PyInstaller y Travis. Actualmente con cada nueva release del proyecto se crea un DRAFT que debería adjuntar el .exe generado por Travis. Este .exe no se encuentra todavía en el DRAFT y sospechamos que es porque el script PyInstaller no funciona adecuadamente

**Comment by enrmerver** [comment]
Los errores encontrados en Snapcraft fueron errores internos puesto que todavía la compatibilidad Travis junto con snapcraft está todavía en una fase experimental.

**Comment by pedbiefre** [comment]
Se ha automatizado la generación del empaquetado del proyecto con éxito. Con cada release del proyecto se crea un DRAFT que contiene el .exe el cual debe de ser colocado en la carpeta raíz del proyecto que se ha de descargar previamente.
